apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: fuseim.pri/ifs # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "true"
mountOptions:
- nolock,tcp,noresvport
- vers=3
reclaimPolicy: Retain  # 回收策略，此处保留卷以进行手动清理 (Delete,Retain)
volumeBindingMode: Immediate
