apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: monitoring
type: Opaque
data: {}
stringData:
  thanos.yaml: |-
    type: s3
    config:
      bucket: prometheus-thanos
      endpoint: minio.minio.svc.cluster.local:9000
      access_key: minio
      secret_key: minio123
      insecure: true
      signature_version2: false
