apiVersion: v1
data: {}
kind: Secret
metadata:
  name: webhook-config
  namespace: monitoring
type: Opaque
stringData:
  config.yml: |-
    targets:
      webhook:
        url: "https://oapi.dingtalk.com/robot/send?access_token=6959e0cea2e54df4f6b40ef1392aa38aefed9faadeaeddf15eb81d736efaff73"
        secret: SEC73bef23c1fc13a32b1dfb9d7bd89fe269828851faca34722dd09a2f9bc62b3ce
        message:
          title: '{{ template "ding.link.title" . }}'
          text: '{{ template "ding.link.content" . }}'
        mention:
          all: true
    templates:
    - /etc/prometheus-webhook-dingtalk/templates/default.tmpl
---
apiVersion: v1
data: {}
kind: Secret
metadata:
  name: webhook-template
  namespace: monitoring
type: Opaque
stringData:
  default.tmpl: |-
    {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
    {{ define "__alertmanagerURL" }}{{ "http://59.110.71.101:59999/alerts" }}/#/alerts?receiver={{ .Receiver }}{{ end }}
    {{ define "default.__text_alert_list" }}{{ range . }}
    ---
    **告警集群:** <font color="#dd0000">KKB-PROD</font><br/>
    **运营团队:** <font color="#dd0000">开课吧运维组</font><br/>
    **告警级别:** <font color="#dd0000">{{ .Labels.severity | upper }}</font><br/>
    **触发时间:** <font color="#dd0000">{{ dateInZone "2006.01.02 15:04:05" (.StartsAt) "Asia/Shanghai" }}</font><br/>
    **事件信息:**
    {{ range .Annotations.SortedPairs }} - {{ .Name }}: <font color="#006666">{{ .Value | markdown | html }}</font><br/>
    {{ end }}
    **事件标签:**
    {{ range .Labels.SortedPairs }}{{ if and (ne (.Name) "severity") (ne (.Name) "summary") (ne (.Name) "team") }} - {{ .Name }}: <font color="#006666">{{ .Value | markdown | html }}</font><br/>
    {{ end }}{{ end }}
    {{ end }}
    {{ end }}
    {{ define "default.__text_alertresovle_list" }}{{ range . }}
    ---
    **告警集群:** <font color="#dd0000">KKB-PROD</font><br/>
    **运营团队:** <font color="#dd0000">开课吧运维组</font><br/>
    **告警级别:** <font color="#dd0000">{{ .Labels.severity | upper }}</font><br/>
    **触发时间:** <font color="#dd0000">{{ dateInZone "2006.01.02 15:04:05" (.StartsAt) "Asia/Shanghai" }}</font><br/>
    **结束时间:** <font color="#00dd00">{{ dateInZone "2006.01.02 15:04:05" (.EndsAt) "Asia/Shanghai" }}</font><br/>
    **事件信息:**
    {{ range .Annotations.SortedPairs }} - {{ .Name }}: <font color="#006666">{{ .Value | markdown | html }}</font><br/>
    {{ end }}
    **事件标签:**
    {{ range .Labels.SortedPairs }}{{ if and (ne (.Name) "severity") (ne (.Name) "summary") (ne (.Name) "team") }} - {{ .Name }}: <font color="#006666">{{ .Value | markdown | html }}</font><br/>
    {{ end }}{{ end }}
    {{ end }}
    {{ end }}
    {{/* Default */}}
    {{ define "default.title" }}{{ template "__subject" . }}{{ end }}
    {{ define "default.content" }}#### \[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}\] **[{{ index .GroupLabels "alertname" }}]({{ template "__alertmanagerURL" . }})**
    {{ if gt (len .Alerts.Firing) 0 -}}
    {{ template "default.__text_alert_list" .Alerts.Firing }}
    {{- end }}
    {{ if gt (len .Alerts.Resolved) 0 -}}
    {{ template "default.__text_alertresovle_list" .Alerts.Resolved }}
    {{- end }}
    {{- end }}
    {{/* Following names for compatibility */}}
    {{ define "ding.link.title" }}{{ template "default.title" . }}{{ end }}
    {{ define "ding.link.content" }}{{ template "default.content" . }}{{ end }}
